name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '/\sdark:[^\s"\]+/'
          replace: " "
          include: "stubs/livewire/resources/views/components/**"
          regex: true